name: PR Check
on:
  pull_request_target:
    types: [opened, synchronize, edited]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "PR title is ${{ github.event.pull_request.title }}"
